name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the code if needed
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Deploy to your server with appleboy/ssh-action
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 164.92.218.59           # Your server’s IP or hostname
          username: root               # The user to SSH as
          key: ${{ secrets.DEPLOY_KEY }}  # Your private key stored in GitHub Secrets
          # For minimal logs, omit `debug: true`
          script: |
            cd /var/www/my-website
            git pull origin main
            npm install
            npm run build
            pm2 restart my-website
