name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ls -la /home/runner/.ssh  # just to confirm the key is there (don't cat it!)


      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 164.92.218.59
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          debug: true
          script: |
            cd /var/www/my-website
            git pull origin main
            npm install
            npm run build
            pm2 restart my-website
          
